const Project = [
    {
        Id: '1',
        pImg: "/images/portfolio/portfolio_item_image_1.webp",
        title: 'Mobile App Design',
        slug: 'Mobile-App-Design',
        sub: 'App Design',
        description: 'Our all-encompassing IELTS Coaching curriculum encompasses every aspect...',
    },
    {
        Id: '2',
        pImg: "/images/portfolio/portfolio_item_image_2.webp",
        title: 'TOEFL Coaching',
        slug: 'TOEFL-Coaching',
        sub: '',
        description: 'Our experienced coaches are not just educators; they are partners in your journey..',
    },
    {
        Id: '3',
        pImg: "/images/portfolio/portfolio_item_image_3.webp",
        title: 'Dashboard Design',
        slug: 'Dashboard-Design',
        sub: 'Web Design',
        description: 'The contents of the citizenship test typically cover a range of subjects ...',
    },
    {
        Id: '4',
        pImg: "/images/portfolio/portfolio_item_image_1.webp",
        title: 'Mobile App Design',
        slug: 'Mobile-App-Design',
        sub: 'App Design',
        description: 'Our all-encompassing IELTS Coaching curriculum encompasses every aspect...',
    },
    {
        Id: '5',
        pImg: "/images/portfolio/portfolio_item_image_2.webp",
        title: 'TOEFL Coaching',
        slug: 'TOEFL-Coaching',
        sub: '',
        description: 'Our experienced coaches are not just educators; they are partners in your journey..',
    },
    {
        Id: '6',
        pImg: "/images/portfolio/portfolio_item_image_3.webp",
        title: 'Dashboard Design',
        slug: 'Dashboard-Design',
        sub: 'Web Design',
        description: 'The contents of the citizenship test typically cover a range of subjects ...',
    },
    {
        Id: '7',
        pImg: "/images/case/case_image_1.webp",
        title: 'About By Digital Minds On',
        description: 'Digital Minds On doesn’t just develop software but solutions that revolutionize an organization’s operations. Our development goal, as your reliable development partner, is to complete unique work that solves today’s problems as well as the vision of tomorrow’s potential. In a world where technology is on the ascent, we should not underestimate the importance of adaptation and foresight in achieving a goal. We provide reliable personnel with years of experience and passion for their work to ensure that every solution offered enhances your success story and builds your competitive edge. Come with me on the exciting performance transformation journey to achieve your organization’s optimum and make your mark in your field.',
    },
    {
        Id: '8',
        pImg: "/images/case/case_image_2.webp",
        title: 'Premier Incredible Services by Digital Minds On Providers',
        description: 'Digital Minds On specializes in delivering cutting-edge software development solutions tailored to meet the unique needs of modern businesses. Our team of experienced developers and designers collaborates to create high-quality, efficient, and scalable applications that drive productivity and innovation. With expertise in web and mobile development, cloud solutions, and custom software, we help businesses streamline operations, enhance user experiences, and achieve their digital transformation goals.',
    },
    {
        Id: '9',
        pImg: "/images/case/case_image_3.webp",
        title: 'Our Mission & Vision',
        description: 'Established in 2022, Digital Minds On is dedicated to providing premier software development solutions that streamline operations and drive growth for businesses across industries. Our advanced technology and skilled team work together to deliver custom software applications, ensuring accuracy, efficiency, and innovation in every project.',
    },
    {
        Id: '10',
        pImg: "/images/portfolio/portfolio_item_image_4.webp",
        title: 'Driving Digital Transformation Explore the Depth of Our IT Projects',
        slug: 'Driving-Digital-Transformation-Explore-the-Depth-of-Our-IT Projects',
        thumb1: 'Logo Design',
        thumb2: 'Finance',
        category: 'technology',
    },
    {
        Id: '17',
        pImg: "/images/portfolio/portfolio_item_image_5.webp",
        title: 'Explore Our IT Solutions Portfolio for Public Sector Organizations',
        slug: 'Explore-Our-IT-Solutions',
        thumb1: 'App Design',
        thumb2: 'Public',
        category:'helpdesk'
    },
    {
        Id: '18',
        pImg: "/images/portfolio/portfolio_item_image_6.webp",
        title: 'Innovative Solutions Showcase the Diversity of Our IT Portfolio',
        slug: 'Innovative-Solutions-Showcase-the-Diversity-of-Our-IT-Portfolio',
        thumb1: 'Card Design',
        thumb2: 'Transpiration',
        category:'analysis'
    },
    {
        Id: '19',
        pImg: "/images/portfolio/portfolio_item_image_7.webp",
        title: 'Tech Triumphs Celebrating Our Achievements in IT Solutions',
        slug: 'Tech-Triumphs-Celebrating-Our-Achievements-in-IT-Solutions',
        thumb1: 'Web Design',
        thumb2: 'Logistic',
        category: 'technology',
    },
    {
        Id: '20',
        pImg: "/images/portfolio/portfolio_item_image_8.webp",
        title: 'Revolutionizing IT Strategies A Closer Look at Our Dynamic IT Solutions',
        slug: 'Revolutionizing-IT-Strategies-A-Closer-Look-at-Our-Dynamic-IT-Solutions',
        thumb1: 'Web Design',
        thumb2: 'Fution',
        category: 'analysis',
    },
    {
        Id: '21',
        pImg: "/images/portfolio/portfolio_item_image_9.webp",
        title: 'Cloud Migration and Integration Project IT Solutions Portfolio',
        slug: 'Cloud-Migration-and-Integration-Project-IT-Solutions-Portfolio',
        thumb1: 'Web Design',
        thumb2: 'Energy',
        category: 'helpdesk'
    },
    {
        Id: '22',
        pImg: "/images/portfolio/portfolio_item_image_10.webp",
        title: 'Pioneering Progress Exploring the Evolution and Impact of',
        slug: 'Pioneering-Progress-Exploring-the-Evolution-and-Impact-of',
        thumb1: 'Web Design',
        thumb2: 'Health',
        category: 'marketing'
    },
    {
        Id: '23',
        pImg: "/images/portfolio/portfolio_item_image_11.webp",
        title: 'Unlocking Potential Explore Our Comprehensive IT Portfolio',
        slug: 'Unlocking-Potential-Explore-Our-Comprehensive-IT-Portfolio',
        thumb1: 'Web Design',
        thumb2: 'Industry',
        category: 'technology',
    },

]

export default Project;